export const PRODUCTS = [
  {
    id: "army-green-tuxedo",
    title: "Army Green Tuxedo",
    desc: "Army Green Tuxedo designed for wedding occasions, featuring a classic style in green, tailored for a refined and modern look.",
    price: "$377.00",
    img: "https://res.cloudinary.com/dcy26s9jm/image/upload/v1774274868/Army_Green_Tuxedo_xtv9bi.webp",
    images: ["https://res.cloudinary.com/dcy26s9jm/image/upload/v1774274868/Army_Green_Tuxedo_xtv9bi.webp"],
    category: "Wedding Collection",
    material: "Tuxedo",
    color: "Green",
    fit: "Slim",
    style: "Classic",
    occasion: "Wedding",
    gender: "Men",
    seoTitle: "Army Green Tuxedo for Men | Premium Tuxedo",
    tags: ["green", "classic", "wedding", "tuxedo"],
    sizes: ["46", "48", "50", "52", "54", "56"],
    rating: 4.8,
    reviewCount: 15,
    reviews: [{ user: "James L.", rating: 5, text: "Exceptional fit and the color is unique." }]
  },
  {
    id: "ash-beige-mens-casual",
    title: "Ash Beige Men's Casual",
    desc: "Ash Beige Men's Casual designed for casual occasions, featuring a minimal style in beige, tailored for a refined and modern look.",
    price: "$101.92",
    img: "https://res.cloudinary.com/dcy26s9jm/image/upload/v1774276103/Ash_Beige_Men_s_Casual_zga6ew.webp",
    images: ["https://res.cloudinary.com/dcy26s9jm/image/upload/v1774276103/Ash_Beige_Men_s_Casual_zga6ew.webp"],
    category: "Casual Collection",
    material: "Smart Casual",
    color: "Beige",
    fit: "Regular",
    style: "Minimal",
    occasion: "Casual",
    gender: "Men",
    seoTitle: "Ash Beige Men's Casual for Men | Premium Casual",
    tags: ["beige", "minimal", "casual", "smart casual"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    rating: 4.6,
    reviewCount: 22,
    reviews: [{ user: "Robert M.", rating: 4, text: "Very comfortable for daily wear." }]
  },
  {
    id: "ash-beige-pinstripe-double-breasted",
    title: "Ash Beige Pinstripe Double Breasted",
    desc: "Ash Beige Pinstripe Double Breasted designed for business occasions, featuring a pinstripe style in beige, tailored for a refined and modern look.",
    price: "$377.00",
    img: "https://res.cloudinary.com/dcy26s9jm/image/upload/v1774276096/Ash_Beige_Pinstripes_Double_Breasted_irm1fl.webp",
    images: ["https://res.cloudinary.com/dcy26s9jm/image/upload/v1774276096/Ash_Beige_Pinstripes_Double_Breasted_irm1fl.webp"],
    category: "Formal Collection",
    material: "Double Breasted",
    color: "Beige",
    fit: "Slim",
    style: "Pinstripe",
    occasion: "Business",
    gender: "Men",
    seoTitle: "Ash Beige Pinstripe Double Breasted for Men | Premium Breasted",
    tags: ["beige", "pinstripe", "business", "double breasted"],
    sizes: ["46", "48", "50", "52", "54", "56"],
    rating: 4.9,
    reviewCount: 12,
    reviews: [{ user: "Alessandro M.", rating: 5, text: "The pinstripe detail is exquisite." }]
  },
  {
    id: "ash-beige-womens-casual",
    title: "Ash Beige Women's Casual",
    desc: "Ash Beige Women's Casual designed for casual occasions, featuring a relaxed style in beige, tailored for a refined and modern look.",
    price: "$168.22",
    img: "https://res.cloudinary.com/dcy26s9jm/image/upload/v1774276096/Ash_Beige_Women_s_Casual_sq12bf.webp",
    images: ["https://res.cloudinary.com/dcy26s9jm/image/upload/v1774276096/Ash_Beige_Women_s_Casual_sq12bf.webp"],
    category: "Casual Collection",
    material: "Casual",
    color: "Beige",
    fit: "Regular",
    style: "Relaxed",
    occasion: "Casual",
    gender: "Women",
    seoTitle: "Ash Beige Women's Casual for Men | Premium Casual",
    tags: ["beige", "relaxed", "casual", "casual"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    rating: 4.7,
    reviewCount: 18,
    reviews: [{ user: "Elena G.", rating: 5, text: "Perfect relaxed fit." }]
  },
  {
    id: "beige-double-breasted-tuxedo",
    title: "Beige Double Breasted Tuxedo",
    desc: "Beige Double Breasted Tuxedo designed for wedding occasions, featuring a double breasted style in beige, tailored for a refined and modern look.",
    price: "$377.00",
    img: "https://res.cloudinary.com/dcy26s9jm/image/upload/v1774276095/Beige_Double_Breasted_Tuxedo_rievwi.webp",
    images: ["https://res.cloudinary.com/dcy26s9jm/image/upload/v1774276095/Beige_Double_Breasted_Tuxedo_rievwi.webp"],
    category: "Wedding Collection",
    material: "Tuxedo",
    color: "Beige",
    fit: "Slim",
    style: "Double Breasted",
    occasion: "Wedding",
    gender: "Men",
    seoTitle: "Beige Double Breasted Tuxedo for Men | Premium Tuxedo",
    tags: ["beige", "double breasted", "wedding", "tuxedo"],
    sizes: ["46", "48", "50", "52", "54", "56"],
    rating: 4.8,
    reviewCount: 9,
    reviews: [{ user: "Julian R.", rating: 5, text: "Classic look with a modern twist." }]
  },
  {
    id: "beige-single-breasted-suit",
    title: "Beige Single Breasted Suit",
    desc: "Beige Single Breasted Suit designed for business occasions, featuring a single breasted style in beige, tailored for a refined and modern look.",
    price: "$312.22",
    img: "https://res.cloudinary.com/dcy26s9jm/image/upload/v1774276095/Beige_Single_Breasted_Suit_bdx4gy.webp",
    images: ["https://res.cloudinary.com/dcy26s9jm/image/upload/v1774276095/Beige_Single_Breasted_Suit_bdx4gy.webp"],
    category: "Formal Collection",
    material: "Suit",
    color: "Beige",
    fit: "Slim",
    style: "Single Breasted",
    occasion: "Business",
    gender: "Men",
    seoTitle: "Beige Single Breasted Suit for Men | Premium Suit",
    tags: ["beige", "single breasted", "business", "suit"],
    sizes: ["46", "48", "50", "52", "54", "56"],
    rating: 4.7,
    reviewCount: 14,
    reviews: [{ user: "David S.", rating: 4, text: "Great quality for the price." }]
  },
  {
    id: "black-pattern-tuxedo",
    title: "Black Pattern Tuxedo",
    desc: "Black Pattern Tuxedo designed for evening occasions, featuring a patterned style in black, tailored for a refined and modern look.",
    price: "$377.00",
    img: "https://res.cloudinary.com/dcy26s9jm/image/upload/v1774276090/Black_Pattern_Tuxedo_upejyb.webp",
    images: ["https://res.cloudinary.com/dcy26s9jm/image/upload/v1774276090/Black_Pattern_Tuxedo_upejyb.webp"],
    category: "Wedding Collection",
    material: "Tuxedo",
    color: "Black",
    fit: "Slim",
    style: "Patterned",
    occasion: "Evening",
    gender: "Men",
    seoTitle: "Black Pattern Tuxedo for Men | Premium Tuxedo",
    tags: ["black", "patterned", "evening", "tuxedo"],
    sizes: ["46", "48", "50", "52", "54", "56"],
    rating: 5.0,
    reviewCount: 7,
    reviews: [{ user: "Marco V.", rating: 5, text: "Stunning pattern, very luxurious." }]
  },
  {
    id: "black-pinstripe-single-breasted",
    title: "Black Pinstripe Single Breasted",
    desc: "Black Pinstripe Single Breasted designed for business occasions, featuring a pinstripe style in black, tailored for a refined and modern look.",
    price: "$312.22",
    img: "https://res.cloudinary.com/dcy26s9jm/image/upload/v1774276089/Black_Pinstripe_Single_Breasted_l8vwjn.webp",
    images: ["https://res.cloudinary.com/dcy26s9jm/image/upload/v1774276089/Black_Pinstripe_Single_Breasted_l8vwjn.webp"],
    category: "Formal Collection",
    material: "Suit",
    color: "Black",
    fit: "Slim",
    style: "Pinstripe",
    occasion: "Business",
    gender: "Men",
    seoTitle: "Black Pinstripe Single Breasted for Men | Premium Breasted",
    tags: ["black", "pinstripe", "business", "suit"],
    sizes: ["46", "48", "50", "52", "54", "56"],
    rating: 4.8,
    reviewCount: 11,
    reviews: [{ user: "Christopher B.", rating: 5, text: "Fits perfectly and looks very sharp." }]
  },
  {
    id: "black-superior-bowtie",
    title: "Black Superior Bowtie",
    desc: "Black Superior Bowtie designed for formal occasions, featuring a classic style in black, tailored for a refined and modern look.",
    price: "$16.82",
    img: "https://res.cloudinary.com/dcy26s9jm/image/upload/v1774276089/Black_Superior_Bowtie_gbnhox.webp",
    images: ["https://res.cloudinary.com/dcy26s9jm/image/upload/v1774276089/Black_Superior_Bowtie_gbnhox.webp"],
    category: "Accessories",
    material: "Bowtie",
    color: "Black",
    fit: "Regular",
    style: "Classic",
    occasion: "Formal",
    gender: "Men",
    seoTitle: "Black Superior Bowtie for Men | Premium Bowtie",
    tags: ["black", "classic", "formal", "bowtie"],
    sizes: ["One Size"],
    rating: 4.9,
    reviewCount: 35,
    reviews: [{ user: "Thomas L.", rating: 5, text: "High quality silk, looks great." }]
  },
  {
    id: "blue-pattern-tuxedo",
    title: "Blue Pattern Tuxedo",
    desc: "Blue Pattern Tuxedo designed for wedding occasions, featuring a patterned style in blue, tailored for a refined and modern look.",
    price: "$377.00",
    img: "https://res.cloudinary.com/dcy26s9jm/image/upload/v1774276089/Blue_Pattern_Tuxedo_esmxez.webp",
    images: ["https://res.cloudinary.com/dcy26s9jm/image/upload/v1774276089/Blue_Pattern_Tuxedo_esmxez.webp"],
    category: "Wedding Collection",
    material: "Tuxedo",
    color: "Blue",
    fit: "Slim",
    style: "Patterned",
    occasion: "Wedding",
    gender: "Men",
    seoTitle: "Blue Pattern Tuxedo for Men | Premium Tuxedo",
    tags: ["blue", "patterned", "wedding", "tuxedo"],
    sizes: ["46", "48", "50", "52", "54", "56"],
    rating: 4.7,
    reviewCount: 8,
    reviews: [{ user: "Sebastian H.", rating: 4, text: "Beautiful color and pattern." }]
  },
  {
    id: "blue-velvet-tuxedo",
    title: "Blue Velvet Tuxedo",
    desc: "Blue Velvet Tuxedo designed for evening occasions, featuring a velvet style in blue, tailored for a refined and modern look.",
    price: "$377.00",
    img: "https://res.cloudinary.com/dcy26s9jm/image/upload/v1774276080/Blue_Velvet_Tuxedo_hhatpx.webp",
    images: ["https://res.cloudinary.com/dcy26s9jm/image/upload/v1774276080/Blue_Velvet_Tuxedo_hhatpx.webp"],
    category: "Wedding Collection",
    material: "Tuxedo",
    color: "Blue",
    fit: "Slim",
    style: "Velvet",
    occasion: "Evening",
    gender: "Men",
    seoTitle: "Blue Velvet Tuxedo for Men | Premium Tuxedo",
    tags: ["blue", "velvet", "evening", "tuxedo"],
    sizes: ["46", "48", "50", "52", "54", "56"],
    rating: 4.9,
    reviewCount: 13,
    reviews: [{ user: "Arthur P.", rating: 5, text: "The velvet is top quality." }]
  },
  {
    id: "charcoal-grey-single-breasted",
    title: "Charcoal Grey Single Breasted",
    desc: "Charcoal Grey Single Breasted designed for business occasions, featuring a classic style in grey, tailored for a refined and modern look.",
    price: "$312.22",
    img: "https://res.cloudinary.com/dcy26s9jm/image/upload/v1774276040/Charcoal_Grey_Single_Breasted_inrewk.webp",
    images: ["https://res.cloudinary.com/dcy26s9jm/image/upload/v1774276040/Charcoal_Grey_Single_Breasted_inrewk.webp"],
    category: "Formal Collection",
    material: "Suit",
    color: "Grey",
    fit: "Slim",
    style: "Classic",
    occasion: "Business",
    gender: "Men",
    seoTitle: "Charcoal Grey Single Breasted for Men | Premium Breasted",
    tags: ["grey", "classic", "business", "suit"],
    sizes: ["46", "48", "50", "52", "54", "56"],
    rating: 4.8,
    reviewCount: 20,
    reviews: [{ user: "James L.", rating: 5, text: "A timeless piece." }]
  },
  {
    id: "classic-black-tuxedo",
    title: "Classic Black Tuxedo",
    desc: "Classic Black Tuxedo designed for wedding occasions, featuring a classic style in black, tailored for a refined and modern look.",
    price: "$377.00",
    img: "https://res.cloudinary.com/dcy26s9jm/image/upload/v1774276040/Classic_Black_Tuxedo_rk4hs6.webp",
    images: ["https://res.cloudinary.com/dcy26s9jm/image/upload/v1774276040/Classic_Black_Tuxedo_rk4hs6.webp"],
    category: "Wedding Collection",
    material: "Tuxedo",
    color: "Black",
    fit: "Slim",
    style: "Classic",
    occasion: "Wedding",
    gender: "Men",
    seoTitle: "Classic Black Tuxedo for Men | Premium Tuxedo",
    tags: ["black", "classic", "wedding", "tuxedo"],
    sizes: ["46", "48", "50", "52", "54", "56"],
    rating: 4.9,
    reviewCount: 25,
    reviews: [{ user: "Robert M.", rating: 5, text: "Can't go wrong with this classic." }]
  },
  {
    id: "classic-double-breasted-grey",
    title: "Classic Double Breasted Grey",
    desc: "Classic Double Breasted Grey designed for business occasions, featuring a classic style in grey, tailored for a refined and modern look.",
    price: "$312.22",
    img: "https://res.cloudinary.com/dcy26s9jm/image/upload/v1774276040/Classic_Double_Breasted_kbryfd.webp",
    images: ["https://res.cloudinary.com/dcy26s9jm/image/upload/v1774276040/Classic_Double_Breasted_kbryfd.webp"],
    category: "Formal Collection",
    material: "Double Breasted",
    color: "Grey",
    fit: "Slim",
    style: "Classic",
    occasion: "Business",
    gender: "Men",
    seoTitle: "Classic Double Breasted Grey for Men | Premium Grey",
    tags: ["grey", "classic", "business", "double breasted"],
    sizes: ["46", "48", "50", "52", "54", "56"],
    rating: 4.7,
    reviewCount: 16,
    reviews: [{ user: "Alessandro M.", rating: 4, text: "Very well made." }]
  },
  {
    id: "classic-offwhite-tuxedo",
    title: "Classic Offwhite Tuxedo",
    desc: "Classic Offwhite Tuxedo designed for wedding occasions, featuring a classic style in offwhite, tailored for a refined and modern look.",
    price: "$332.22",
    img: "https://res.cloudinary.com/dcy26s9jm/image/upload/v1774276038/Classic_offwhite_Tuxedo_nazeuv.webp",
    images: ["https://res.cloudinary.com/dcy26s9jm/image/upload/v1774276038/Classic_offwhite_Tuxedo_nazeuv.webp"],
    category: "Wedding Collection",
    material: "Tuxedo",
    color: "Offwhite",
    fit: "Slim",
    style: "Classic",
    occasion: "Wedding",
    gender: "Men",
    seoTitle: "Classic Offwhite Tuxedo for Men | Premium Tuxedo",
    tags: ["offwhite", "classic", "wedding", "tuxedo"],
    sizes: ["46", "48", "50", "52", "54", "56"],
    rating: 4.8,
    reviewCount: 10,
    reviews: [{ user: "Elena G.", rating: 5, text: "Elegant and unique." }]
  },
  {
    id: "coffee-brown-mens-casual",
    title: "Coffee Brown Men's Casual",
    desc: "Coffee Brown Men's Casual designed for casual occasions, featuring a relaxed style in brown, tailored for a refined and modern look.",
    price: "$101.92",
    img: "https://res.cloudinary.com/dcy26s9jm/image/upload/v1774276038/Coffee_Brown_Men_s_Casual_rlrvvk.webp",
    images: ["https://res.cloudinary.com/dcy26s9jm/image/upload/v1774276038/Coffee_Brown_Men_s_Casual_rlrvvk.webp"],
    category: "Casual Collection",
    material: "Smart Casual",
    color: "Brown",
    fit: "Regular",
    style: "Relaxed",
    occasion: "Casual",
    gender: "Men",
    seoTitle: "Coffee Brown Men's Casual for Men | Premium Casual",
    tags: ["brown", "relaxed", "casual", "smart casual"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    rating: 4.5,
    reviewCount: 19,
    reviews: [{ user: "Julian R.", rating: 4, text: "Good for everyday wear." }]
  },
  {
    id: "coffee-brown-womens-casual",
    title: "Coffee Brown Women's Casual",
    desc: "Coffee Brown Women's Casual designed for casual occasions, featuring a relaxed style in brown, tailored for a refined and modern look.",
    price: "$168.22",
    img: "https://res.cloudinary.com/dcy26s9jm/image/upload/v1774275975/Coffee_Brown_Women_s_Casual_qemzbx.webp",
    images: ["https://res.cloudinary.com/dcy26s9jm/image/upload/v1774275975/Coffee_Brown_Women_s_Casual_qemzbx.webp"],
    category: "Casual Collection",
    material: "Casual",
    color: "Brown",
    fit: "Regular",
    style: "Relaxed",
    occasion: "Casual",
    gender: "Women",
    seoTitle: "Coffee Brown Women's Casual for Men | Premium Casual",
    tags: ["brown", "relaxed", "casual", "casual"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    rating: 4.6,
    reviewCount: 15,
    reviews: [{ user: "David S.", rating: 4, text: "Nice color and fit." }]
  },
  {
    id: "cream-pattern-tuxedo",
    title: "Cream Pattern Tuxedo",
    desc: "Cream Pattern Tuxedo designed for wedding occasions, featuring a patterned style in cream, tailored for a refined and modern look.",
    price: "$377.00",
    img: "https://res.cloudinary.com/dcy26s9jm/image/upload/v1774275960/Cream_Pattern_Tuxedo_nfv4jq.webp",
    images: ["https://res.cloudinary.com/dcy26s9jm/image/upload/v1774275960/Cream_Pattern_Tuxedo_nfv4jq.webp"],
    category: "Wedding Collection",
    material: "Tuxedo",
    color: "Cream",
    fit: "Slim",
    style: "Patterned",
    occasion: "Wedding",
    gender: "Men",
    seoTitle: "Cream Pattern Tuxedo for Men | Premium Tuxedo",
    tags: ["cream", "patterned", "wedding", "tuxedo"],
    sizes: ["46", "48", "50", "52", "54", "56"],
    rating: 4.9,
    reviewCount: 6,
    reviews: [{ user: "Marco V.", rating: 5, text: "The pattern is very subtle and elegant." }]
  },
  {
    id: "park-windowpane-charcoal-grey",
    title: "Park Windowpane Charcoal Grey",
    desc: "Park Windowpane Charcoal Grey designed for business occasions, featuring a windowpane style in grey, tailored for a refined and modern look.",
    price: "$312.22",
    img: "https://res.cloudinary.com/dcy26s9jm/image/upload/v1774275959/Dark_Windowpane_Charcoal_Grey_xeyrtj.webp",
    images: ["https://res.cloudinary.com/dcy26s9jm/image/upload/v1774275959/Dark_Windowpane_Charcoal_Grey_xeyrtj.webp"],
    category: "Formal Collection",
    material: "Suit",
    color: "Grey",
    fit: "Slim",
    style: "Windowpane",
    occasion: "Business",
    gender: "Men",
    seoTitle: "Park Windowpane Charcoal Grey for Men | Premium Grey",
    tags: ["grey", "windowpane", "business", "suit"],
    sizes: ["46", "48", "50", "52", "54", "56"],
    rating: 4.8,
    reviewCount: 12,
    reviews: [{ user: "Christopher B.", rating: 5, text: "Love the windowpane detail." }]
  },
  {
    id: "deep-red-double-breasted",
    title: "Deep Red Double Breasted",
    desc: "Deep Red Double Breasted designed for wedding occasions, featuring a classic style in red, tailored for a refined and modern look.",
    price: "$332.22",
    img: "https://res.cloudinary.com/dcy26s9jm/image/upload/v1774275958/Deep_Red_Double_Breasted_irenry.webp",
    images: ["https://res.cloudinary.com/dcy26s9jm/image/upload/v1774275958/Deep_Red_Double_Breasted_irenry.webp"],
    category: "Formal Collection",
    material: "Double Breasted",
    color: "Red",
    fit: "Slim",
    style: "Classic",
    occasion: "Wedding",
    gender: "Men",
    seoTitle: "Deep Red Double Breasted for Men | Premium Breasted",
    tags: ["red", "classic", "wedding", "double breasted"],
    sizes: ["46", "48", "50", "52", "54", "56"],
    rating: 4.7,
    reviewCount: 9,
    reviews: [{ user: "Thomas L.", rating: 4, text: "Very bold and stylish." }]
  },
  {
    id: "double-breasted-bold-red",
    title: "Double Breasted Bold Red",
    desc: "Double Breasted Bold Red designed for evening occasions, featuring a bold style in red, tailored for a refined and modern look.",
    price: "$377.00",
    img: "https://res.cloudinary.com/dcy26s9jm/image/upload/v1774275958/Double_Breasted_Bold_Red_i2h99b.webp",
    images: ["https://res.cloudinary.com/dcy26s9jm/image/upload/v1774275958/Double_Breasted_Bold_Red_i2h99b.webp"],
    category: "Formal Collection",
    material: "Double Breasted",
    color: "Red",
    fit: "Slim",
    style: "Bold",
    occasion: "Evening",
    gender: "Women",
    seoTitle: "Double Breasted Bold Red for Men | Premium Red",
    tags: ["red", "bold", "evening", "double breasted"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    rating: 4.9,
    reviewCount: 5,
    reviews: [{ user: "Sebastian H.", rating: 5, text: "A real head-turner." }]
  },
  {
    id: "double-breasted-offwhite-stripes",
    title: "Double Breasted Offwhite Stripes",
    desc: "Double Breasted Offwhite Stripes designed for wedding occasions, featuring a striped style in offwhite, tailored for a refined and modern look.",
    price: "$332.22",
    img: "https://res.cloudinary.com/dcy26s9jm/image/upload/v1774275959/Double_Breasted_Offwhite_Stripes_jcz4pf.webp",
    images: ["https://res.cloudinary.com/dcy26s9jm/image/upload/v1774275959/Double_Breasted_Offwhite_Stripes_jcz4pf.webp"],
    category: "Wedding Collection",
    material: "Double Breasted",
    color: "Offwhite",
    fit: "Slim",
    style: "Striped",
    occasion: "Wedding",
    gender: "Men",
    seoTitle: "Double Breasted Offwhite Stripes for Men | Premium Stripes",
    tags: ["offwhite", "striped", "wedding", "double breasted"],
    sizes: ["46", "48", "50", "52", "54", "56"],
    rating: 4.6,
    reviewCount: 11,
    reviews: [{ user: "Arthur P.", rating: 4, text: "Great for a beach wedding." }]
  },
  {
    id: "fine-red-pinstripe-single-breasted",
    title: "Fine Red Pinstripe Single Breasted",
    desc: "Fine Red Pinstripe Single Breasted designed for business occasions, featuring a pinstripe style in red, tailored for a refined and modern look.",
    price: "$312.22",
    img: "https://res.cloudinary.com/dcy26s9jm/image/upload/v1774275957/Fine_Red_Pinstripes_Single_Breasted_by11ev.webp",
    images: ["https://res.cloudinary.com/dcy26s9jm/image/upload/v1774275957/Fine_Red_Pinstripes_Single_Breasted_by11ev.webp"],
    category: "Formal Collection",
    material: "Suit",
    color: "Red",
    fit: "Slim",
    style: "Pinstripe",
    occasion: "Business",
    gender: "Men",
    seoTitle: "Fine Red Pinstripe Single Breasted for Men | Premium Breasted",
    tags: ["red", "pinstripe", "business", "suit"],
    sizes: ["46", "48", "50", "52", "54", "56"],
    rating: 4.8,
    reviewCount: 14,
    reviews: [{ user: "James L.", rating: 5, text: "The pinstripe is very fine and subtle." }]
  },
  {
    id: "green-pattern-tuxedo",
    title: "Green Pattern Tuxedo",
    desc: "Green Pattern Tuxedo designed for evening occasions, featuring a patterned style in green, tailored for a refined and modern look.",
    price: "$377.00",
    img: "https://res.cloudinary.com/dcy26s9jm/image/upload/v1774275951/Green_Pattern_Tuxedo_o2tker.webp",
    images: ["https://res.cloudinary.com/dcy26s9jm/image/upload/v1774275951/Green_Pattern_Tuxedo_o2tker.webp"],
    category: "Wedding Collection",
    material: "Tuxedo",
    color: "Green",
    fit: "Slim",
    style: "Patterned",
    occasion: "Evening",
    gender: "Men",
    seoTitle: "Green Pattern Tuxedo for Men | Premium Tuxedo",
    tags: ["green", "patterned", "evening", "tuxedo"],
    sizes: ["46", "48", "50", "52", "54", "56"],
    rating: 4.7,
    reviewCount: 7,
    reviews: [{ user: "Robert M.", rating: 4, text: "Unique color and pattern." }]
  },
  {
    id: "grey-pattern-windowpane",
    title: "Grey Pattern Windowpane",
    desc: "Grey Pattern Windowpane designed for business occasions, featuring a windowpane style in grey, tailored for a refined and modern look.",
    price: "$312.22",
    img: "https://res.cloudinary.com/dcy26s9jm/image/upload/v1774275950/Light_Grey_Single_Breasted_vb2jb1.webp",
    images: ["https://res.cloudinary.com/dcy26s9jm/image/upload/v1774275950/Light_Grey_Single_Breasted_vb2jb1.webp"],
    category: "Formal Collection",
    material: "Suit",
    color: "Grey",
    fit: "Slim",
    style: "Windowpane",
    occasion: "Business",
    gender: "Men",
    seoTitle: "Grey Pattern Windowpane for Men | Premium Windowpane",
    tags: ["grey", "windowpane", "business", "suit"],
    sizes: ["46", "48", "50", "52", "54", "56"],
    rating: 4.8,
    reviewCount: 16,
    reviews: [{ user: "Alessandro M.", rating: 5, text: "Great fit and style." }]
  },
  {
    id: "light-beige-windowpane-3-piece",
    title: "Light Beige Windowpane 3 Piece",
    desc: "Light Beige Windowpane 3 Piece designed for wedding occasions, featuring a windowpane style in beige, tailored for a refined and modern look.",
    price: "$332.22",
    img: "https://res.cloudinary.com/dcy26s9jm/image/upload/v1774275951/Light_Beige_WindowPane_3_pieces_p1qneq.webp",
    images: ["https://res.cloudinary.com/dcy26s9jm/image/upload/v1774275951/Light_Beige_WindowPane_3_pieces_p1qneq.webp"],
    category: "Wedding Collection",
    material: "Suit",
    color: "Beige",
    fit: "Slim",
    style: "Windowpane",
    occasion: "Wedding",
    gender: "Men",
    seoTitle: "Light Beige Windowpane 3 Piece for Men | Premium Piece",
    tags: ["beige", "windowpane", "wedding", "suit"],
    sizes: ["46", "48", "50", "52", "54", "56"],
    rating: 4.9,
    reviewCount: 12,
    reviews: [{ user: "Elena G.", rating: 5, text: "The 3-piece look is very sharp." }]
  },
  {
    id: "light-grey-single-breasted",
    title: "Light Grey Single Breasted",
    desc: "Light Grey Single Breasted designed for business occasions, featuring a classic style in grey, tailored for a refined and modern look.",
    price: "$312.22",
    img: "https://res.cloudinary.com/dcy26s9jm/image/upload/v1774275950/Light_Grey_Single_Breasted_vb2jb1.webp",
    images: ["https://res.cloudinary.com/dcy26s9jm/image/upload/v1774275950/Light_Grey_Single_Breasted_vb2jb1.webp"],
    category: "Formal Collection",
    material: "Suit",
    color: "Grey",
    fit: "Slim",
    style: "Classic",
    occasion: "Business",
    gender: "Men",
    seoTitle: "Light Grey Single Breasted for Men | Premium Breasted",
    tags: ["grey", "classic", "business", "suit"],
    sizes: ["46", "48", "50", "52", "54", "56"],
    rating: 4.7,
    reviewCount: 18,
    reviews: [{ user: "Julian R.", rating: 4, text: "Good quality and fit." }]
  },
  {
    id: "nehru-suit-dark-brown",
    title: "Nehru Suit Dark Brown",
    desc: "Nehru Suit Dark Brown designed for formal occasions, featuring a nehru style in brown, tailored for a refined and modern look.",
    price: "$377.00",
    img: "https://res.cloudinary.com/dcy26s9jm/image/upload/v1774275949/Nehru_Suit_Dark_Brown_zgkldo.webp",
    images: ["https://res.cloudinary.com/dcy26s9jm/image/upload/v1774275949/Nehru_Suit_Dark_Brown_zgkldo.webp"],
    category: "Wedding Collection",
    material: "Ethnic",
    color: "Brown",
    fit: "Slim",
    style: "Nehru",
    occasion: "Formal",
    gender: "Men",
    seoTitle: "Nehru Suit Dark Brown for Men | Premium Brown",
    tags: ["brown", "nehru", "formal", "ethnic"],
    sizes: ["46", "48", "50", "52", "54", "56"],
    rating: 4.8,
    reviewCount: 10,
    reviews: [{ user: "David S.", rating: 5, text: "Very unique and well-made." }]
  },
  {
    id: "nehru-suit-dark-purple",
    title: "Nehru Suit Dark Purple",
    desc: "Nehru Suit Dark Purple designed for formal occasions, featuring a nehru style in purple, tailored for a refined and modern look.",
    price: "$377.00",
    img: "https://res.cloudinary.com/dcy26s9jm/image/upload/v1774275949/Nehru_Suit_Dark_Purple_bbbszl.webp",
    images: ["https://res.cloudinary.com/dcy26s9jm/image/upload/v1774275949/Nehru_Suit_Dark_Purple_bbbszl.webp"],
    category: "Wedding Collection",
    material: "Ethnic",
    color: "Purple",
    fit: "Slim",
    style: "Nehru",
    occasion: "Formal",
    gender: "Men",
    seoTitle: "Nehru Suit Dark Purple for Men | Premium Purple",
    tags: ["purple", "nehru", "formal", "ethnic"],
    sizes: ["46", "48", "50", "52", "54", "56"],
    rating: 4.9,
    reviewCount: 7,
    reviews: [{ user: "Marco V.", rating: 5, text: "The color is stunning." }]
  },
  {
    id: "offwhite-cream-single-breasted",
    title: "Offwhite Cream Single Breasted",
    desc: "Offwhite Cream Single Breasted designed for wedding occasions, featuring a classic style in cream, tailored for a refined and modern look.",
    price: "$262.22",
    img: "https://res.cloudinary.com/dcy26s9jm/image/upload/v1774275948/Off-white_Cream_Stone_Single_Breasted_ymokmb.webp",
    images: ["https://res.cloudinary.com/dcy26s9jm/image/upload/v1774275948/Off-white_Cream_Stone_Single_Breasted_ymokmb.webp"],
    category: "Wedding Collection",
    material: "Suit",
    color: "Cream",
    fit: "Slim",
    style: "Classic",
    occasion: "Wedding",
    gender: "Men",
    seoTitle: "Offwhite Cream Single Breasted for Men | Premium Breasted",
    tags: ["cream", "classic", "wedding", "suit"],
    sizes: ["46", "48", "50", "52", "54", "56"],
    rating: 4.7,
    reviewCount: 15,
    reviews: [{ user: "Christopher B.", rating: 4, text: "Perfect for a summer wedding." }]
  },
  {
    id: "offwhite-baggy-single-breasted",
    title: "Offwhite Baggy Single Breasted",
    desc: "Offwhite Baggy Single Breasted designed for casual occasions, featuring a relaxed style in offwhite, tailored for a refined and modern look.",
    price: "$177.00",
    img: "https://res.cloudinary.com/dcy26s9jm/image/upload/v1774275939/Offwhite_Baggy_Single_Breasted_hjv6co.webp",
    images: ["https://res.cloudinary.com/dcy26s9jm/image/upload/v1774275939/Offwhite_Baggy_Single_Breasted_hjv6co.webp"],
    category: "Casual Collection",
    material: "Suit",
    color: "Offwhite",
    fit: "Loose",
    style: "Relaxed",
    occasion: "Casual",
    gender: "Women",
    seoTitle: "Offwhite Baggy Single Breasted for Men | Premium Breasted",
    tags: ["offwhite", "relaxed", "casual", "suit"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    rating: 4.6,
    reviewCount: 12,
    reviews: [{ user: "Thomas L.", rating: 4, text: "Very comfortable and stylishly loose." }]
  },
  {
    id: "striped-double-breasted-navy-blue",
    title: "Striped Double Breasted Navy Blue",
    desc: "Striped Double Breasted Navy Blue designed for business occasions, featuring a striped style in navy, tailored for a refined and modern look.",
    price: "$312.22",
    img: "https://res.cloudinary.com/dcy26s9jm/image/upload/v1774275938/Stripes_Double_Breasted_Navy_Blue_wlwka4.webp",
    images: ["https://res.cloudinary.com/dcy26s9jm/image/upload/v1774275938/Stripes_Double_Breasted_Navy_Blue_wlwka4.webp"],
    category: "Formal Collection",
    material: "Double Breasted",
    color: "Navy",
    fit: "Slim",
    style: "Striped",
    occasion: "Business",
    gender: "Men",
    seoTitle: "Striped Double Breasted Navy Blue for Men | Premium Blue",
    tags: ["navy", "striped", "business", "double breasted"],
    sizes: ["46", "48", "50", "52", "54", "56"],
    rating: 4.8,
    reviewCount: 20,
    reviews: [{ user: "Sebastian H.", rating: 5, text: "A classic business look." }]
  },
  {
    id: "super-double-tuxedo-black",
    title: "Super Double Tuxedo Black",
    desc: "Super Double Tuxedo Black designed for evening occasions, featuring a luxury style in black, tailored for a refined and modern look.",
    price: "$377.00",
    img: "https://res.cloudinary.com/dcy26s9jm/image/upload/v1774275936/Super_Double_Tuxedo_iu82bo.webp",
    images: ["https://res.cloudinary.com/dcy26s9jm/image/upload/v1774275936/Super_Double_Tuxedo_iu82bo.webp"],
    category: "Wedding Collection",
    material: "Tuxedo",
    color: "Black",
    fit: "Slim",
    style: "Luxury",
    occasion: "Evening",
    gender: "Men",
    seoTitle: "Super Double Tuxedo Black for Men | Premium Black",
    tags: ["black", "luxury", "evening", "tuxedo"],
    sizes: ["46", "48", "50", "52", "54", "56"],
    rating: 5.0,
    reviewCount: 8,
    reviews: [{ user: "Arthur P.", rating: 5, text: "The ultimate tuxedo." }]
  },
  {
    id: "teal-blue-single-breasted",
    title: "Teal Blue Single Breasted",
    desc: "Teal Blue Single Breasted designed for business occasions, featuring a classic style in teal, tailored for a refined and modern look.",
    price: "$312.22",
    img: "https://res.cloudinary.com/dcy26s9jm/image/upload/v1774275936/Teal_Blue_Single_Breasted_ylv3bi.webp",
    images: ["https://res.cloudinary.com/dcy26s9jm/image/upload/v1774275936/Teal_Blue_Single_Breasted_ylv3bi.webp"],
    category: "Formal Collection",
    material: "Suit",
    color: "Teal",
    fit: "Slim",
    style: "Classic",
    occasion: "Business",
    gender: "Men",
    seoTitle: "Teal Blue Single Breasted for Men | Premium Breasted",
    tags: ["teal", "classic", "business", "suit"],
    sizes: ["46", "48", "50", "52", "54", "56"],
    rating: 4.7,
    reviewCount: 14,
    reviews: [{ user: "James L.", rating: 4, text: "Nice color and fit." }]
  },
  {
    id: "ultraflex-high-rise-suit",
    title: "UltraFlex High-Rise Suit",
    desc: "UltraFlex High-Rise Suit designed for business occasions, featuring a modern style in grey, tailored for a refined and modern look.",
    price: "$312.22",
    img: "https://res.cloudinary.com/dcy26s9jm/image/upload/v1774275937/UltraFlex_High-Rise_e5ohhb.webp",
    images: ["https://res.cloudinary.com/dcy26s9jm/image/upload/v1774275937/UltraFlex_High-Rise_e5ohhb.webp"],
    category: "Formal Collection",
    material: "Suit",
    color: "Grey",
    fit: "Slim",
    style: "Modern",
    occasion: "Business",
    gender: "Men",
    seoTitle: "UltraFlex High-Rise Suit for Men | Premium Suit",
    tags: ["grey", "modern", "business", "suit"],
    sizes: ["46", "48", "50", "52", "54", "56"],
    rating: 4.9,
    reviewCount: 10,
    reviews: [{ user: "Robert M.", rating: 5, text: "Incredibly comfortable for all-day wear." }]
  },
  {
    id: "velvet-tuxedo-green",
    title: "Velvet Tuxedo Green",
    desc: "Velvet Tuxedo Green designed for evening occasions, featuring a velvet style in green, tailored for a refined and modern look.",
    price: "$377.00",
    img: "https://res.cloudinary.com/dcy26s9jm/image/upload/v1774277286/Velvet_Tuxedo_green_dzbxkh.webp",
    images: ["https://res.cloudinary.com/dcy26s9jm/image/upload/v1774277286/Velvet_Tuxedo_green_dzbxkh.webp"],
    category: "Wedding Collection",
    material: "Tuxedo",
    color: "Green",
    fit: "Slim",
    style: "Velvet",
    occasion: "Evening",
    gender: "Men",
    seoTitle: "Velvet Tuxedo Green for Men | Premium Green",
    tags: ["green", "velvet", "evening", "tuxedo"],
    sizes: ["46", "48", "50", "52", "54", "56"],
    rating: 4.8,
    reviewCount: 6,
    reviews: [{ user: "Alessandro M.", rating: 5, text: "The velvet is very rich." }]
  },
  {
    id: "velvet-tuxedo-red",
    title: "Velvet Tuxedo Red",
    desc: "Velvet Tuxedo Red designed for evening occasions, featuring a velvet style in red, tailored for a refined and modern look.",
    price: "$377.00",
    img: "https://res.cloudinary.com/dcy26s9jm/image/upload/v1774277367/Velvet_Tuxedo_red_nohgoq.webp",
    images: ["https://res.cloudinary.com/dcy26s9jm/image/upload/v1774277367/Velvet_Tuxedo_red_nohgoq.webp"],
    category: "Wedding Collection",
    material: "Tuxedo",
    color: "Red",
    fit: "Slim",
    style: "Velvet",
    occasion: "Evening",
    gender: "Men",
    seoTitle: "Velvet Tuxedo Red for Men | Premium Red",
    tags: ["red", "velvet", "evening", "tuxedo"],
    sizes: ["46", "48", "50", "52", "54", "56"],
    rating: 4.9,
    reviewCount: 9,
    reviews: [{ user: "Elena G.", rating: 5, text: "Stunning color and feel." }]
  },
  {
    id: "wedding-shirt",
    title: "Wedding Shirt",
    desc: "Wedding Shirt designed for wedding occasions, featuring a classic style in white, tailored for a refined and modern look.",
    price: "$61.15",
    img: "https://res.cloudinary.com/dcy26s9jm/image/upload/v1774277484/Wedding_Shirt_mdvmpw.webp",
    images: ["https://res.cloudinary.com/dcy26s9jm/image/upload/v1774277484/Wedding_Shirt_mdvmpw.webp"],
    category: "Accessories",
    material: "Shirt",
    color: "White",
    fit: "Regular",
    style: "Classic",
    occasion: "Wedding",
    gender: "Men",
    seoTitle: "Wedding Shirt for Men | Premium Shirt",
    tags: ["white", "classic", "wedding", "shirt"],
    sizes: ["One Size"],
    rating: 4.7,
    reviewCount: 30,
    reviews: [{ user: "Julian R.", rating: 4, text: "Good quality cotton." }]
  },
  {
    id: "windowpane-navy-blue",
    title: "Windowpane Navy Blue",
    desc: "Windowpane Navy Blue designed for business occasions, featuring a windowpane style in navy, tailored for a refined and modern look.",
    price: "$312.22",
    img: "https://res.cloudinary.com/dcy26s9jm/image/upload/v1774277580/WindowPane_Navy_Blue_Double_Breasted_qk3wbi.webp",
    images: ["https://res.cloudinary.com/dcy26s9jm/image/upload/v1774277580/WindowPane_Navy_Blue_Double_Breasted_qk3wbi.webp"],
    category: "Formal Collection",
    material: "Suit",
    color: "Navy",
    fit: "Slim",
    style: "Windowpane",
    occasion: "Business",
    gender: "Men",
    seoTitle: "Windowpane Navy Blue for Men | Premium Blue",
    tags: ["navy", "windowpane", "business", "suit"],
    sizes: ["46", "48", "50", "52", "54", "56"],
    rating: 4.8,
    reviewCount: 17,
    reviews: [{ user: "David S.", rating: 5, text: "Love the navy windowpane." }]
  }
];

export const CATEGORIES = ["All", "Wedding Collection", "Casual Collection", "Formal Collection", "Accessories"];
export const GENDERS = ["All", "Men", "Women"];
export const OCCASIONS = ["All", "Wedding", "Casual", "Business", "Evening", "Formal"];
export const FITS = ["All", "Slim", "Regular", "Loose"];
export const STYLES = ["All", "Classic", "Minimal", "Pinstripe", "Relaxed", "Double Breasted", "Patterned", "Bold", "Striped", "Luxury", "Modern", "Nehru", "Velvet", "Windowpane"];
export const ITEMS_PER_PAGE = 12;

export const SIZES: Record<string, string[]> = {
  "Wedding Collection": ["46", "48", "50", "52", "54", "56"],
  "Formal Collection": ["46", "48", "50", "52", "54", "56"],
  "Casual Collection": ["S", "M", "L", "XL", "XXL"],
  "Accessories": ["One Size"]
};
